### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by LoadHack** [Ampdale/WZ-UAV#2]
I tried 03.11.2021 the product did not work

**Comment by Ampdale** [comment]
Did you wait till you were actually in a match and then inject it?

**Comment by LoadHack** [comment]
I did it during the match
, write to me in the discard KUL_IK#8849

**Comment by LoadHack** [comment]
in what mode does it work?

**Comment by Ampdale** [comment]
windowed mode only

**Comment by LoadHack** [comment]
![Uploading Screenshot_2.png…]()

**Comment by LoadHack** [comment]
https://ibb.co/dK2YQJt

**Comment by Ampdale** [comment]
I updated the offsets, it should be working now
